name: Check analytics

on:
  schedule:
    - cron: '0 23 * * *'

  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.5

      - name: Install dependencies
        run: npm install

      - name: Проверка обновлённых сделок
        run: node .github/scripts/check.js
        env:
          BITRIX_INCOMING_WEBHOOK: ${{ secrets.BITRIX_INCOMING_WEBHOOK }}
