name: Force update deals analytics

on:
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.5

      - name: Install dependencies
        run: npm install

      - name: Принудительное обновление сделок
        run: node .github/scripts/update.js
        env:
          BITRIX_INCOMING_WEBHOOK: ${{ secrets.BITRIX_INCOMING_WEBHOOK }}
          UPDATE_FROM_DATE: ${{ secrets.UPDATE_FROM_DATE }}
